import JobsList from "@/components/JobsList";
import { SharedCarousel } from "@/components/shared/carousel/carousel";
import { FilterProvider } from "@/contexts/FilterProvider";
import { CompanyJobs } from "@/interfaces/CompanyJobs";

const carouselArray: CompanyJobs[] = [
  {
    company: "TechNova",
    companyImg:
      "https://images.pexels.com/photos/4820659/pexels-photo-4820659.jpeg?auto=compress&cs=tinysrgb&w=800",
    openings: [
      {
        jobId: "1",
        title: "Software Engineer",
        salary: "3-4LPA",
        postingDate: "01/15/2023",
        location: "San Francisco, CA",
        jobType: "Full time",
        experience: "2+ yrs",
        domain: "Software",
      },
      {
        jobId: "2",
        title: "Data Scientist",
        salary: "7-8LPA",
        postingDate: "02/10/2023",
        location: "San Francisco, CA",
        jobType: "Full time",
        experience: "3+ yrs",
        domain: "Data Science",
      },
      {
        jobId: "3",
        title: "Product Manager",
        salary: "8-9LPA",
        postingDate: "03/05/2023",
        location: "San Francisco, CA",
        jobType: "Full time",
        experience: "5+ yrs",
        domain: "Product Management",
      },
      {
        jobId: "4",
        title: "UX Designer",
        salary: "5-6LPA",
        postingDate: "04/20/2023",
        location: "San Francisco, CA",
        jobType: "Full time",
        experience: "4+ yrs",
        domain: "Design",
      },
      {
        jobId: "5",
        title: "DevOps Engineer",
        salary: "6.5-7.5LPA",
        postingDate: "05/15/2023",
        location: "San Francisco, CA",
        jobType: "Full time",
        experience: "3+ yrs",
        domain: "DevOps",
      },
      {
        jobId: "6",
        title: "QA Engineer",
        salary: "5.5-6.5LPA",
        postingDate: "06/10/2023",
        location: "San Francisco, CA",
        jobType: "Full time",
        experience: "2+ yrs",
        domain: "Quality Assurance",
      },
    ],
  },
  {
    company: "GreenLeaf",
    companyImg:
      "https://images.pexels.com/photos/4820659/pexels-photo-4820659.jpeg?auto=compress&cs=tinysrgb&w=800",
    openings: [
      {
        jobId: "1",
        title: "Software Engineer",
        salary: "6-7LPA",
        postingDate: "01/15/2023",
        location: "San Francisco, CA",
        jobType: "Full time",
        experience: "2+ yrs",
        domain: "Software",
      },
      {
        jobId: "2",
        title: "Data Scientist",
        salary: "7-8LPA",
        postingDate: "02/10/2023",
        location: "San Francisco, CA",
        jobType: "Full time",
        experience: "3+ yrs",
        domain: "Data Science",
      },
      {
        jobId: "3",
        title: "Product Manager",
        salary: "8-9LPA",
        postingDate: "03/05/2023",
        location: "San Francisco, CA",
        jobType: "Full time",
        experience: "5+ yrs",
        domain: "Product Management",
      },
      {
        jobId: "4",
        title: "UX Designer",
        salary: "5-6LPA",
        postingDate: "04/20/2023",
        location: "San Francisco, CA",
        jobType: "Full time",
        experience: "4+ yrs",
        domain: "Design",
      },
      {
        jobId: "5",
        title: "DevOps Engineer",
        salary: "6.5-7.5LPA",
        postingDate: "05/15/2023",
        location: "San Francisco, CA",
        jobType: "Full time",
        experience: "3+ yrs",
        domain: "DevOps",
      },
      {
        jobId: "6",
        title: "QA Engineer",
        salary: "5.5-6.5LPA",
        postingDate: "06/10/2023",
        location: "San Francisco, CA",
        jobType: "Full time",
        experience: "2+ yrs",
        domain: "Quality Assurance",
      },
    ],
  },
  {
    company: "HealthPlus",
    companyImg:
      "https://images.pexels.com/photos/4820659/pexels-photo-4820659.jpeg?auto=compress&cs=tinysrgb&w=800",
    openings: [
      {
        jobId: "1",
        title: "Software Engineer",
        salary: "6-7LPA",
        postingDate: "01/15/2023",
        location: "San Francisco, CA",
        jobType: "Full time",
        experience: "2+ yrs",
        domain: "Software",
      },
      {
        jobId: "2",
        title: "Data Scientist",
        salary: "7-8LPA",
        postingDate: "02/10/2023",
        location: "San Francisco, CA",
        jobType: "Full time",
        experience: "3+ yrs",
        domain: "Data Science",
      },
      {
        jobId: "3",
        title: "Product Manager",
        salary: "8-9LPA",
        postingDate: "03/05/2023",
        location: "San Francisco, CA",
        jobType: "Full time",
        experience: "5+ yrs",
        domain: "Product Management",
      },
      {
        jobId: "4",
        title: "UX Designer",
        salary: "5-6LPA",
        postingDate: "04/20/2023",
        location: "San Francisco, CA",
        jobType: "Full time",
        experience: "4+ yrs",
        domain: "Design",
      },
      {
        jobId: "5",
        title: "DevOps Engineer",
        salary: "6.5-7.5LPA",
        postingDate: "05/15/2023",
        location: "San Francisco, CA",
        jobType: "Full time",
        experience: "3+ yrs",
        domain: "DevOps",
      },
      {
        jobId: "6",
        title: "QA Engineer",
        salary: "5.5-6.5LPA",
        postingDate: "06/10/2023",
        location: "San Francisco, CA",
        jobType: "Full time",
        experience: "2+ yrs",
        domain: "Quality Assurance",
      },
    ],
  },
  {
    company: "FinWise",
    companyImg:
      "https://images.pexels.com/photos/4567890/pexels-photo-4567890.jpeg?auto=compress&cs=tinysrgb&w=800",
    openings: [
      {
        jobId: "1",
        title: "Software Engineer",
        salary: "6-7LPA",
        postingDate: "01/15/2023",
        location: "San Francisco, CA",
        jobType: "Full time",
        experience: "2+ yrs",
        domain: "Software",
      },
      {
        jobId: "2",
        title: "Data Scientist",
        salary: "7-8LPA",
        postingDate: "02/10/2023",
        location: "San Francisco, CA",
        jobType: "Full time",
        experience: "3+ yrs",
        domain: "Data Science",
      },
      {
        jobId: "3",
        title: "Product Manager",
        salary: "8-9LPA",
        postingDate: "03/05/2023",
        location: "San Francisco, CA",
        jobType: "Full time",
        experience: "5+ yrs",
        domain: "Product Management",
      },
      {
        jobId: "4",
        title: "UX Designer",
        salary: "5-6LPA",
        postingDate: "04/20/2023",
        location: "San Francisco, CA",
        jobType: "Full time",
        experience: "4+ yrs",
        domain: "Design",
      },
      {
        jobId: "5",
        title: "DevOps Engineer",
        salary: "6.5-7.5LPA",
        postingDate: "05/15/2023",
        location: "San Francisco, CA",
        jobType: "Full time",
        experience: "3+ yrs",
        domain: "DevOps",
      },
      {
        jobId: "6",
        title: "QA Engineer",
        salary: "5.5-6.5LPA",
        postingDate: "06/10/2023",
        location: "San Francisco, CA",
        jobType: "Full time",
        experience: "2+ yrs",
        domain: "Quality Assurance",
      },
    ],
  },
  {
    company: "EcoBuild",
    companyImg:
      "https://images.pexels.com/photos/5678901/pexels-photo-5678901.jpeg?auto=compress&cs=tinysrgb&w=800",
    openings: [
      {
        jobId: "1",
        title: "Software Engineer",
        salary: "6-7LPA",
        postingDate: "01/15/2023",
        location: "San Francisco, CA",
        jobType: "Full time",
        experience: "2+ yrs",
        domain: "Software",
      },
      {
        jobId: "2",
        title: "Data Scientist",
        salary: "7-8LPA",
        postingDate: "02/10/2023",
        location: "San Francisco, CA",
        jobType: "Full time",
        experience: "3+ yrs",
        domain: "Data Science",
      },
      {
        jobId: "3",
        title: "Product Manager",
        salary: "8-9LPA",
        postingDate: "03/05/2023",
        location: "San Francisco, CA",
        jobType: "Full time",
        experience: "5+ yrs",
        domain: "Product Management",
      },
      {
        jobId: "4",
        title: "UX Designer",
        salary: "5-6LPA",
        postingDate: "04/20/2023",
        location: "San Francisco, CA",
        jobType: "Full time",
        experience: "4+ yrs",
        domain: "Design",
      },
      {
        jobId: "5",
        title: "DevOps Engineer",
        salary: "6.5-7.5LPA",
        postingDate: "05/15/2023",
        location: "San Francisco, CA",
        jobType: "Full time",
        experience: "3+ yrs",
        domain: "DevOps",
      },
      {
        jobId: "6",
        title: "QA Engineer",
        salary: "5.5-6.5LPA",
        postingDate: "06/10/2023",
        location: "San Francisco, CA",
        jobType: "Full time",
        experience: "2+ yrs",
        domain: "Quality Assurance",
      },
    ],
  },
  {
    company: "EduSmart",
    companyImg:
      "https://images.pexels.com/photos/6789012/pexels-photo-6789012.jpeg?auto=compress&cs=tinysrgb&w=800",
    openings: [
      {
        jobId: "1",
        title: "Software Engineer",
        salary: "6-7LPA",
        postingDate: "01/15/2023",
        location: "San Francisco, CA",
        jobType: "Full time",
        experience: "2+ yrs",
        domain: "Software",
      },
      {
        jobId: "2",
        title: "Data Scientist",
        salary: "7-8LPA",
        postingDate: "02/10/2023",
        location: "San Francisco, CA",
        jobType: "Full time",
        experience: "3+ yrs",
        domain: "Data Science",
      },
      {
        jobId: "3",
        title: "Product Manager",
        salary: "8-9LPA",
        postingDate: "03/05/2023",
        location: "San Francisco, CA",
        jobType: "Full time",
        experience: "5+ yrs",
        domain: "Product Management",
      },
      {
        jobId: "4",
        title: "UX Designer",
        salary: "5-6LPA",
        postingDate: "04/20/2023",
        location: "San Francisco, CA",
        jobType: "Full time",
        experience: "4+ yrs",
        domain: "Design",
      },
      {
        jobId: "5",
        title: "DevOps Engineer",
        salary: "6.5-7.5LPA",
        postingDate: "05/15/2023",
        location: "San Francisco, CA",
        jobType: "Full time",
        experience: "3+ yrs",
        domain: "DevOps",
      },
      {
        jobId: "6",
        title: "QA Engineer",
        salary: "5.5-6.5LPA",
        postingDate: "06/10/2023",
        location: "San Francisco, CA",
        jobType: "Full time",
        experience: "2+ yrs",
        domain: "Quality Assurance",
      },
    ],
  },
  {
    company: "TravelSphere",
    companyImg:
      " https://images.pexels.com/photos/7890123/pexels-photo-7890123.jpeg?auto=compress&cs=tinysrgb&w=800",
    openings: [
      {
        jobId: "1",
        title: "Software Engineer",
        salary: "6-7LPA",
        postingDate: "01/15/2023",
        location: "San Francisco, CA",
        jobType: "Full time",
        experience: "2+ yrs",
        domain: "Software",
      },
      {
        jobId: "2",
        title: "Data Scientist",
        salary: "7-8LPA",
        postingDate: "02/10/2023",
        location: "San Francisco, CA",
        jobType: "Full time",
        experience: "3+ yrs",
        domain: "Data Science",
      },
      {
        jobId: "3",
        title: "Product Manager",
        salary: "8-9LPA",
        postingDate: "03/05/2023",
        location: "San Francisco, CA",
        jobType: "Full time",
        experience: "5+ yrs",
        domain: "Product Management",
      },
      {
        jobId: "4",
        title: "UX Designer",
        salary: "5-6LPA",
        postingDate: "04/20/2023",
        location: "San Francisco, CA",
        jobType: "Full time",
        experience: "4+ yrs",
        domain: "Design",
      },
      {
        jobId: "5",
        title: "DevOps Engineer",
        salary: "6.5-7.5LPA",
        postingDate: "05/15/2023",
        location: "San Francisco, CA",
        jobType: "Full time",
        experience: "3+ yrs",
        domain: "DevOps",
      },
      {
        jobId: "6",
        title: "QA Engineer",
        salary: "5.5-6.5LPA",
        postingDate: "06/10/2023",
        location: "San Francisco, CA",
        jobType: "Full time",
        experience: "2+ yrs",
        domain: "Quality Assurance",
      },
    ],
  },
];

import dynamic from "next/dynamic";

const NoSsrJobFilters = dynamic(() => import("../components/JobFilters"), {
  ssr: false,
});
export default function Home() {
  return (
    <main className="flex flex-col gap-4">
      <SharedCarousel data={carouselArray} />
      <div className="flex flex-col-reverse md:flex-row mx-4 gap-4 md:px-12">
        <JobsList />
        <FilterProvider>
          <NoSsrJobFilters />
        </FilterProvider>
      </div>
    </main>
  );
}
